### ISSUE TITLE
Error: Failed to start container

### ISSUE THREAD

**Issue by scbmw017** [chipzoller/pks-rancher-reg#2]
I'm not sure if this is an issue or if its me so I will explain the problem and hopefully you can help.

I followed your instructions to the letter only adding in a storageclass.yml and pvc.yml with a name of rancherca after I performed the pks create-cluster and noticed that the pods were in an Init:Error state when I ran the kubectl get pods.  I also had to change the image from chipzoller/pks-rancher-reg:1.0 to chipzoller/pks-rancher-reg

I then ran kubectl delete job.batch/pks-rancher-reg to delete everything after I added in the storageclass.yml and pvc.yml.  I then ran kubectl apply -f pks-rancher-reg.yml which recreated the pods but they now have this error:  Init:ContainerCannotRun

When I run the command kubectl describe pod pks-rancher-reg-wwjpp I receive the following attached
![Screen Shot 2019-10-18 at 1 35 04 PM](https://user-images.githubusercontent.com/47151934/67115473-4c670680-f1ac-11e9-861c-1b870b07c47c.png)
 error:

Any help would be appreciated

PKS version 1.5.0
Rancher version 2.2.6

**Comment by chipzoller** [comment]
I'm seeing the same thing when I pull the image from Docker Hub as well (permission denied). I'll look into this and see what's going on.

**Comment by chipzoller** [comment]
Problem was the script was node made executable in the image hence the permission error. Dockerfile updated which has triggered a new build and push to Docker Hub, and I've verified by pulling this image that it is working. If you test this out on your existing PKS cluster, note that you may need to add the `imagePullPolicy: Always` to the `initContainers` as well as `containers` objects in the Pod spec.

Please try again and tell me the results.
